apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mdb
spec:
  type: LoadBalancer
  loadBalancerIP: 161.97.165.65  # Presuming environment supports specifying this
  ports:
    - name: http
      protocol: TCP
      port: 80  # The external service port
      targetPort: 80  # The pod's port where the service sends traffic
  selector:
    app: frontend
